### ISSUE TITLE
Faraday::ConnectionFailed error

### ISSUE THREAD

**Issue by Bajinai** [unixcharles/acme-client#102]
I've been using this gem without problems previously, but now that it's time to renew my certificates, i've run into a Faraday::ConnectionFailed execution expired error. It happens whenever i try to register my private key (and if i omit that, it happens on authorize).

Code snippet;

```
endpoint = 'https://acme-staging.api.letsencrypt.org/directory'
private_key = OpenSSL::PKey::RSA.new(4096)
client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options:{ request: { open_timeout: 5, timeout: 5}})
registration = client.register(contact: 'mailto:baji@gmail.com')
```

Stack trace below;

```
`Faraday::ConnectionFailed: execution expired
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:106:in `get_nonce'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:99:in `pop_nonce'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:15:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client.rb:55:in `authorize'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:63:in `block (3 levels) in <top (required)>'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:60:in `each'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:60:in `block (2 levels) in <top (required)>'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
Net::OpenTimeout: execution expired
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:32:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/request/url_encoded.rb:15:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `head'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday.rb:99:in `method_missing'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:106:in `get_nonce'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:99:in `pop_nonce'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client/faraday_middleware.rb:15:in `call'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/acme-client-0.3.7/lib/acme/client.rb:55:in `authorize'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:63:in `block (3 levels) in <top (required)>'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:60:in `each'
/home/alexander/Desktop/capdesk/source/capdesk/lib/tasks/obtain_ssl.rake:60:in `block (2 levels) in <top (required)>'
/home/alexander/.rvm/gems/ruby-2.3.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'`
```

**Comment by unixcharles** [comment]
`Faraday::ConnectionFailed execution expired error` happen when your connection timeout.

You seem to be using the staging endpoint. Try with production.

**Comment by Bajinai** [comment]
I should maybe have stated, that i have tried both with the staging and production endpoint.

However it seems to be something with Ubuntu 16.04 (even a complete fresh install) and not this gem - tried using the letsencrypt certbot manually which gave me the same problem, however running it on OSX succeeded, so i guess it's not really an issue of this particular gem :-)

**Comment by paradisaeidae** [comment]
I've encountered similar symptoms with Ubuntu 16.04 using other utilities. It sometimes has to do with ipv6 dns be‎ing attempted.Apt-get has an option to force the use for ip4 dns.Remove ipv6 dns entries in resolv.conf to test this theory.

**Comment by Bajinai** [comment]
Changing to ipv4 dns for Ubuntu 16.04 solved the issue, thank you!

**Comment by paradisaeidae** [comment]
There is an edit to /etc/gai.conf which survives reboots: http://askubuntu.com/questions/32298/prefer-a-ipv4-dns-lookups-before-aaaaipv6-lookups#38468

**Comment by matthewbjones** [comment]
@unixcharles This is happening to me on OS X (10.12.3) Ruby 2.2.2, both against the staging and production endpoints. Still trying to figure out what's going on but wanted to re-raise this issue.

**Comment by unixcharles** [comment]
`Faraday::ConnectionFailed` basically wrap `Net::OpenTimeout` when used with `Net::HTTP`.

This is a standard network connectivity issue.

I'm not sure why you would not be able to reach letsencrypt servers but its probably not related to the gem itself.

You could try to connect to their server with Net::HTTP directly to have a better understanding of that is going on.

**Comment by matthewbjones** [comment]
That's correct. Ultimately, we determined that it was the Internet connection / ISP, and specifically something to do with IPv6, per the previous discussions on this Issue.

On OS X, you can get close to disabling IPv6 by going to "System Preferences" -> "Network" -> "Advanced" -> "Configure IPv6" and setting it to "Link-local only"

Writing how to do this here so other people who may come across this Issue will know how to workaround the problem on OS X if they encounter it.
