### ISSUE TITLE
Undefined method exception when getting authorization (in decode_link_headers)

### ISSUE THREAD

**Issue by jeromegn** [unixcharles/acme-client#114]
Relevant backtrace:

```
gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:87:in `decode_link_headers': undefined method `split' for {"next"=>"https://acme-v01.api.letsencrypt.org/acme/new-cert"}:Hash (NoMethodError)
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:29:in `on_complete'
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `block in call'
    from gems/faraday-0.11.0/lib/faraday/response.rb:61:in `on_complete'
    from gems/acme-client-0.5.1/lib/acme/client/faraday_middleware.rb:18:in `call'
    from gems/faraday-0.11.0/lib/faraday/rack_builder.rb:139:in `build_response'
    from gems/faraday-0.11.0/lib/faraday/connection.rb:377:in `run_request'
    from gems/faraday-0.11.0/lib/faraday/connection.rb:140:in `get'
    from gems/acme-client-0.5.1/lib/acme/client.rb:63:in `fetch_authorization'
```

Looks like it's expecting a string but getting a hash.

Not sure if it matters, but I'm running it in a docker container (alpine 3.4) using ruby 2.4.0.

I can dig in for more details if necessary.

**Comment by unixcharles** [comment]
Hey, salut Jerome!

This is quite strange. It look like your links already been parsed. Do you have a Faraday middleware doing that for you somehow?

**Comment by jeromegn** [comment]
Salut :)

We don't have any other faraday middleware.

Maybe I'm doing something screwy. I wonder if some object may be memoized and kept around...

We can't reproduce it here and it seems to only have happened once while our system was in a weird state. If it crops back up, I'll bump this issue back up!

**Comment by unixcharles** [comment]
Maybe find out if have some class loaded somewhere that implement web linking (rfc5988).

You could do something like:

```ruby
ObjectSpace.each_object(Class).select { |klass| klass < Faraday::Middleware }
```

**Comment by jeromegn** [comment]
So, this happened again :)

```
gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:91:in `decode_link_headers': undefined method `split' for {"next"=>"https://acme-v01.api.letsencrypt.org/acme/new-cert"}:Hash (NoMethodError)
    from gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:29:in `on_complete'
    from gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:18:in `block in call'
    from gems/faraday-0.12.0.1/lib/faraday/response.rb:61:in `on_complete'
    from gems/acme-client-0.5.5/lib/acme/client/faraday_middleware.rb:18:in `call'
    from gems/faraday-0.12.0.1/lib/faraday/rack_builder.rb:139:in `build_response'
    from gems/faraday-0.12.0.1/lib/faraday/connection.rb:386:in `run_request'
    from gems/faraday-0.12.0.1/lib/faraday/connection.rb:149:in `get'
    from gems/acme-client-0.5.5/lib/acme/client.rb:63:in `fetch_authorization'
```

Running that ObjectSpace line in production, I got:

```ruby
Faraday::Response::Middleware
Faraday::Adapter
Acme::Client::FaradayMiddleware
Pipetree::Railway
Trailblazer::Operation::Pipetree::Railway
Faraday::Adapter::NetHttp
Faraday::Request::UrlEncoded
```

I'm not sure why Trailblazer or Pipetree show up in there. I can't find a mention of faraday in their codebase. Anyway, we're getting rid of Trailblazer.

A subsequent call to `fetch_authorization` works. I'm not sure why this happens. Probably something due to our own code. I'll close this for now!
