### ISSUE TITLE
Error when register with an ECDSA account key

### ISSUE THREAD

**Issue by sdaubert** [unixcharles/acme-client#117]
I am trying to register with an ECDSA key.
I modified `Acme::Client::Crypto#initialize` to avoid problems encountered in #111:
```ruby
  def initialize(private_key)
    if private_key.is_a?(OpenSSL::PKey::EC) && RbConfig::CONFIG['MAJOR'] == '2' &&
       RbConfig::CONFIG['MINOR'].to_i < 4
      @private_key = Acme::Client::CertificateRequest::ECKeyPatch.new(private_key)
    else
      @private_key = private_key
    end
  end
```

In my code, when calling `client.register`, I have this exception:
```
Acme::Client::Error::Malformed: JWS verification error
         # ./lib/acme/client/faraday_middleware.rb:43:in `raise_on_error!'
         # ./lib/acme/client/faraday_middleware.rb:33:in `on_complete'
         # ./lib/acme/client/faraday_middleware.rb:18:in `block in call'
         # ./vendor/bundle/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/response.rb:61:in `on_complete'
         # ./lib/acme/client/faraday_middleware.rb:18:in `call'
         # ./vendor/bundle/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/rack_builder.rb:139:in `build_response'
         # ./vendor/bundle/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:377:in `run_request'
         # ./vendor/bundle/ruby/2.3.0/gems/faraday-0.10.0/lib/faraday/connection.rb:177:in `post'
         # ./lib/acme/client.rb:45:in `register'
```

I may provide a PR with updated Crypto code and a spec on Acme::Client#register, if you need it.

**Comment by unixcharles** [comment]
This is quite the rabbit hole 🤕

**Comment by sdaubert** [comment]
Sorry, i am not a native english speaker, and I don't understand what you mean.

**Comment by unixcharles** [comment]
Les problèmes avec les clés ECDSA semble être sans fin.

**Comment by sdaubert** [comment]
I added a PR (#118) with my code, if you have time to investigate. I have very little knowledge about JWS.

**Comment by sdaubert** [comment]
Nice.
I will test this soon.
