### ISSUE TITLE
Timeout doesn't appear to work

### ISSUE THREAD

**Issue by catphish** [unixcharles/acme-client#121]
Not sure if this is a problem with acme-client, Faraday, or net/http, but the timeout doesn't appear to work.

```
irb(main):010:0> client.connection
=> #<Faraday::Connection:0x00000002633268 @parallel_manager=nil, @headers={"User-Agent"=>"Faraday v0.9.2"}, @params={}, @options=#<Faraday::RequestOptions timeout=5, open_timeout=5>, @ssl=#<Faraday::SSLOptions (empty)>, @default_parallel_manager=nil, @builder=#<Faraday::RackBuilder:0x00000002632c78 @handlers=[Acme::Client::FaradayMiddleware, Faraday::Adapter::NetHttp], @app=#<Acme::Client::FaradayMiddleware:0x00000001e66cb0 @app=#<Faraday::Adapter::NetHttp:0x00000001e66d78 @app=#<Proc:0x00000001e67318@/opt/acme-manager/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:152 (lambda)>>, @client=#<Acme::Client:0x00000002652a28 @connection_options={:request=>{:open_timeout=>5, :timeout=>5}}, @directory_uri=nil, @private_key=#<OpenSSL::PKey::RSA:0x00000002652ac8>, @endpoint="https://acme-v01.api.letsencrypt.org/", @nonces=[], @operation_endpoints={"new-authz"=>"/acme/new-authz", "new-cert"=>"/acme/new-cert", "new-reg"=>"/acme/new-reg", "revoke-cert"=>"/acme/revoke-cert"}, @connection=#<Faraday::Connection:0x00000002633268 ...>>, @env=#<Faraday::Env @method=:get @url=#<URI::HTTPS https://acme-v01.api.letsencrypt.org/> @request=#<Faraday::RequestOptions timeout=5, open_timeout=5> @request_headers={"User-Agent"=>"Acme::Client v0.5.5 (https://github.com/unixcharles/acme-client)"} @ssl=#<Faraday::SSLOptions (empty)>>, @crypto=#<Acme::Client::Crypto:0x00000001e648e8 @private_key=#<OpenSSL::PKey::RSA:0x00000002652ac8>>>>, @url_prefix=#<URI::HTTPS https://acme-v01.api.letsencrypt.org/>, @proxy=nil>
irb(main):011:0> Timeout.timeout(10) do
irb(main):012:1* client.connection.get
irb(main):013:1> end
Timeout::Error: execution expired
	from /usr/lib/ruby/2.3.0/net/protocol.rb:158:in `wait_readable'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
	from /usr/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
	from /usr/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
	from /usr/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
	from /usr/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1407:in `request'
	from /usr/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
	from /usr/lib/ruby/2.3.0/net/http.rb:853:in `start'
	from /usr/lib/ruby/2.3.0/net/http.rb:1398:in `request'
	from /opt/acme-manager/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:82:in `perform_request'
	from /opt/acme-manager/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:40:in `block in call'
	from /opt/acme-manager/vendor/bundle/ruby/2.3.0/gems/faraday-0.9.2/lib/faraday/adapter/net_http.rb:87:in `with_net_http_connection'
... 15 levels...
	from /usr/bin/irb:11:in `<top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /var/lib/gems/2.3.0/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
	from /usr/local/bin/bundle:22:in `load'
	from /usr/local/bin/bundle:22:in `<main>'

```

**Comment by jhass** [comment]
In general [do not use timeout](http://blog.headius.com/2008/02/rubys-threadraise-threadkill-timeoutrb.html)

You should be able to set a timeout in `Acme::Client.new`s `connection_options` argument.

**Comment by catphish** [comment]
Sorry, perhaps I should have made my example must clearer. I added `Timeout.timeout(10)` here only to demonstrate that `#<Faraday::RequestOptions timeout=5, open_timeout=5>` is not being triggered.

**Comment by jhass** [comment]
Oh I see. I think this is an upstream issue, either faraday or net/http. Did you try to swap `Faraday.default_adapter` with anything else?

**Comment by catphish** [comment]
I'm afraid I don't know how to do that in this context? Any chance of an example i can use to replace:

```
client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options: { request: { open_timeout: 5, timeout: 5 } })
```

**Comment by jhass** [comment]
There's a [`Faraday::default_adapter=`](https://github.com/lostisland/faraday/blob/master/lib/faraday.rb#L85)

**Comment by catphish** [comment]
Changing the default adapter to Patron resolved the problem for me. `Net::HTTP` and `HTTPClient` both fail to honour the timeout.

```
Faraday::default_adapter = :patron
```

**Comment by catphish** [comment]
Unfortunately, it seems that with this "fix" in place, much more serious problems occur. On almost every request, one of the following 2 errors occur:

```
Acme::Client::Error::BadNonce: JWS has no anti-replay nonce
```

```
Acme::Client::Error::BadNonce: Error message: <HTML><HEAD>\n<TITLE>Bad Request</TITLE>\n</HEAD><BODY>\n<H1>Bad Request</H1>\nYour browser sent a request that this server could not understand.<P>\nReference&#32;&#35;7&#46;3b367a5c&#46;1495456414&#46;0\n</BODY>\n</HTML>\n"
```

I will have to switch back to `net/http` for now :(

**Comment by unixcharles** [comment]
Not too sure why the timeout is not working. Technically, it just forward the options to `Faraday#new` [here](https://github.com/unixcharles/acme-client/blob/master/lib/acme/client.rb#L89).

I see that you are using a somewhat older version of Farday (0.9.2). Did you try upgrading?

> Unfortunately, it seems that with this "fix" in place, much more serious problems occur. On almost every request, one of the following 2 errors occur:

This does not seem like an error related to the `BadNonce`, I think the wrong error message is bubbling up. I'll try to reproduce it.

**Comment by herberzt** [comment]
Can you provide me a small snippet on how to use `Faraday::default_adapter=` instead? I am a little confused on what you mean.

**Comment by herberzt** [comment]
so I ended up adding the following before calling `Acme::Client.new` which seems to be working expectedly 
```
  Faraday.default_connection_options = {request: { open_timeout: 5, timeout: 5 }}
  Faraday.default_adapter = :httpclient
  Faraday.default_connection = Faraday::Connection.new(nil, Faraday.default_connection_options)
```

@catphish this might help you

**Comment by catphish** [comment]
I'm afraid haven't had an opportunity to look at this further. Thank you very much both for the advice. I will try to test this with various adapters again including an updated Faraday.
