### ISSUE TITLE
Two steps validation script

### ISSUE THREAD

**Issue by Soullivaneuh** [unixcharles/acme-client#48]
I'm trying to use our library to manage a "two steps" certificate validation:

1. Challenge file creation (`acme_01.rb`):

```ruby
# We're going to need a private key.
require 'openssl'
private_key = OpenSSL::PKey::RSA.new(2048)

File.write('private_key', private_key)

print private_key

# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint = 'https://acme-v01.api.letsencrypt.org/'

# Initialize the client
require 'acme/client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint)

# If the private key is not known to the server, we need to register it for the first time.
registration = client.register(contact: 'mailto:soullivaneuh@gmail.com')

# You'll may need to agree to the term (that's up the to the server to require it or not but boulder does by default)
registration.agree_terms

# Let's try to optain a certificate for example.org

# We need to prove that we control the domain using one of the challenges method.
authorization = client.authorize(domain: 'sullivansenechal.com')

# For now the only challenge method supprted by the client is http-01.
challenge = authorization.http01

# The http-01 method will require you to response to an HTTP request.

# You can retrieve the expected path for the file.
challenge.filename # => ".well-known/acme-challenge/:some_token"

# You can generate the body of the expected response.
challenge.file_content # => 'string token and JWK thumbprint'

# You can send no Content-Type at all but if you send one it has to be 'text/plain'.
challenge.content_type

# Save the file. We'll create a public directory to serve it from, and we'll creating the challenge directory.
FileUtils.mkdir_p( File.join( 'public', File.dirname( challenge.filename ) ) )

# Then writing the file
File.write( File.join( 'public', challenge.filename), challenge.file_content )
```

This one will just generate a private key, save it and get challenge file name and content.

After that, I'll push the challenge file to the server of the hosted domain.

2. Validate the challenge (`acme_02.rb`):

```ruby
# We're going to need a private key.
require 'openssl'
key_file = File.new('private_key')
private_key = key_file.read()

print private_key

# We need an ACME server to talk to, see github.com/letsencrypt/boulder
endpoint = 'https://acme-v01.api.letsencrypt.org/'

# Initialize the client
require 'acme/client'
client = Acme::Client.new(private_key: private_key.to_s, endpoint: endpoint)

# If the private key is not known to the server, we need to register it for the first time.
registration = client.register(contact: 'mailto:soullivaneuh@gmail.com')

# You'll may need to agree to the term (that's up the to the server to require it or not but boulder does by default)
registration.agree_terms

# Let's try to optain a certificate for example.org

# We need to prove that we control the domain using one of the challenges method.
authorization = client.authorize(domain: 'sullivansenechal.com')

# For now the only challenge method supprted by the client is http-01.
challenge = authorization.http01

# The http-01 method will require you to response to an HTTP request.

# You can retrieve the expected path for the file.
challenge.filename # => ".well-known/acme-challenge/:some_token"

# You can generate the body of the expected response.
challenge.file_content # => 'string token and JWK thumbprint'

print challenge.filename

# You can send no Content-Type at all but if you send one it has to be 'text/plain'.
challenge.content_type

# Save the file. We'll create a public directory to serve it from, and we'll creating the challenge directory.
FileUtils.mkdir_p( File.join( 'public', File.dirname( challenge.filename ) ) )

# Then writing the file
File.write( File.join( 'public', challenge.filename), challenge.file_content )

# The challenge file can be server with a Ruby webserver such as run a webserver in another console. You may need to forward ports on your router
#ruby -run -e httpd public -p 8080 --bind-address 0.0.0.0


# Once you are ready to serve the confirmation request you can proceed.
challenge.request_verification # => true
challenge.verify_status # => 'pending'

# Wait a bit for the server to make the request, or really just blink, it should be fast.
sleep(1)

challenge.verify_status # => 'valid'

# We're going to need a certificate signing request. If not explicitly
# specified, the first name listed becomes the common name.
csr = Acme::Client::CertificateRequest.new(names: %w[example.org www.example.org])

# We can now request a certificate, you can pass anything that returns
# a valid DER encoded CSR when calling to_der on it, for example a
# OpenSSL::X509::Request too.
certificate = client.new_certificate(csr) # => #<Acme::Client::Certificate ....>

# Save the certificate and key
File.write("privkey.pem", certificate.request.private_key.to_pem)
File.write("cert.pem", certificate.to_pem)
File.write("chain.pem", certificate.chain_to_pem)
File.write("fullchain.pem", certificate.fullchain_to_pem)
```

This file will get the previously generated private key and do the same as the first script but, with validation.

But when running `acme_02.rb`, I got the following error:

```ruby
$ bundle exec ruby acme_02.rb
/home/sullivan/tmp/acme-client/lib/acme/client/crypto.rb:31:in `public_key': undefined method `public_key' for #<String:0x000000021e30f0> (NoMethodError)
	from /home/sullivan/tmp/acme-client/lib/acme/client/crypto.rb:27:in `jwk'
	from /home/sullivan/tmp/acme-client/lib/acme/client/crypto.rb:11:in `generate_signed_jws'
	from /home/sullivan/tmp/acme-client/lib/acme/client/faraday_middleware.rb:11:in `call'
	from /home/sullivan/tmp/acme-client/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/sullivan/tmp/acme-client/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /home/sullivan/tmp/acme-client/vendor/bundle/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
	from /home/sullivan/tmp/acme-client/lib/acme/client.rb:25:in `register'
	from acme_02.rb:16:in `<main>'
```

I can't find any documentation to separate the challenge process, maybe could you give me a clue?

**Comment by jhass** [comment]
Simply restore the private key with
```rb
private_key = OpenSSL::PKey::RSA.new(File.read("private_key"))
```

**Comment by unixcharles** [comment]
Thanks @jhass
