### ISSUE TITLE
Parse error reading JWS

### ISSUE THREAD

**Issue by szymonpk** [unixcharles/acme-client#68]
I'm basically running through readme and I'm not sure why this is happening. (using any other email address doesn't help)

```
require 'openssl'
private_key = OpenSSL::PKey::RSA.new(4096)
endpoint = "https://acme-staging.api.letsencrypt.org/"

require 'acme-client'
client = Acme::Client.new(private_key: private_key, endpoint: endpoint)
registration = client.register(contact: 'mailto:contact@example.com')
Acme::Client::Error::Malformed: Parse error reading JWS
        from /usr/lib64/ruby/gems/2.2.0/gems/acme-client-0.3.1/lib/acme/client/faraday_middleware.rb:35:in `raise_on_error!'
        from /usr/lib64/ruby/gems/2.2.0/gems/acme-client-0.3.1/lib/acme/client/faraday_middleware.rb:25:in `on_complete'
        from /usr/lib64/ruby/gems/2.2.0/gems/acme-client-0.3.1/lib/acme/client/faraday_middleware.rb:12:in `block in call'
        from /usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /usr/lib64/ruby/gems/2.2.0/gems/acme-client-0.3.1/lib/acme/client/faraday_middleware.rb:12:in `call'
        from /usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /usr/lib64/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /usr/lib64/ruby/gems/2.2.0/gems/acme-client-0.3.1/lib/acme/client.rb:25:in `register'
        from (irb):9
        from /usr/bin/irb:11:in `<main>'
```

**Comment by szymonpk** [comment]
Found it, with json-jwt 1.2.4 (@env.body)[https://github.com/unixcharles/acme-client/blob/master/lib/acme/client/faraday_middleware.rb#L11] isn't encrypted properly and it looks like this: `"{\"resource\":\"new-reg\",\"contact\":[\"mailto:contact@example.com\"]}"`, where it should have keys like this `"{\"protected\":\"<protected hash>\",\"signature\":\"<signature hash>\"}"`. Upgrading json-jwt to 1.5.x helps.
