### ISSUE TITLE
issue when initializing client

### ISSUE THREAD

**Issue by ryanstout** [unixcharles/acme-client#7]
I tried running the stuff in the readme, but when I try to make Acme::Client, I get an error because directory isn't a keyword arg.  (There is a directory_uri arg though, so I assume it got renamed)  However when I run the following from the readme, I get:

```
client = Acme::Client.new(private_key: private_key, endpoint: endpoint, directory_uri: './certs')
NoMethodError: undefined method `gsub' for nil:NilClass
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/acme-client-d08c04140f3a/lib/acme/faraday_middleware.rb:39:in `on_complete'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/acme-client-d08c04140f3a/lib/acme/faraday_middleware.rb:12:in `block in call'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/acme-client-d08c04140f3a/lib/acme/faraday_middleware.rb:12:in `call'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:140:in `get'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/acme-client-d08c04140f3a/lib/acme/client.rb:59:in `load_directory!'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/acme-client-d08c04140f3a/lib/acme/client.rb:13:in `initialize'
	from (irb):14:in `new'
	from (irb):14
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli/console.rb:14:in `run'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:308:in `console'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/cli.rb:10:in `start'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:20:in `block in <top (required)>'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
	from /Users/ryanstout/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/bundler-1.10.6/bin/bundle:18:in `<top (required)>'
	from /Users/ryanstout/.rbenv/versions/2.2.0/bin/bundle:23:in `load'
	from /Users/ryanstout/.rbenv/versions/2.2.0/bin/bundle:23:in `<main>'irb
```

Thanks!

**Comment by unixcharles** [comment]
Sorry about that. I just removed it from the readme.

The directory is mean be an URL where you can fetch the endpoint list from the server, its [rfc.section.6.2](https://letsencrypt.github.io/acme-spec/#rfc.section.6.2) (sorry for linking a RFC document, I'm not sure but I would just assume that it has to be rude by any standard)

Its just confusing to have it on the readme since, while its something that is part of the spec, but in practice its always the same. At the moment, the only implementation of ACME on server is boulder, so using the default paths for the endpoint is just fine.

I need to come up with a better API / terminology for this in the future, I don't want consumer of the lib to have to guess that kind of details.

Let me know if everything work well for you.
