### ISSUE TITLE
README example fails with "algorithm 'none' in JWS header not acceptable"

### ISSUE THREAD

**Issue by mpalmer** [unixcharles/acme-client#74]
Doing (as far as I can tell) exactly what the README tells me to:

```
$ gem install acme-client
Fetching: securecompare-1.0.0.gem (100%)
Successfully installed securecompare-1.0.0
Fetching: bindata-2.3.1.gem (100%)
Successfully installed bindata-2.3.1
Fetching: url_safe_base64-0.2.2.gem (100%)
Successfully installed url_safe_base64-0.2.2
Fetching: json-jwt-1.6.2.gem (100%)
Successfully installed json-jwt-1.6.2
Fetching: acme-client-0.3.3.gem (100%)
Successfully installed acme-client-0.3.3
5 gems installed
$ irb
>> require 'openssl'
=> true
>> private_key = OpenSSL::PKey::RSA.new(4096)
=> #<OpenSSL::PKey::RSA:0x00000001708fb8>
>> endpoint = 'https://acme-staging.api.letsencrypt.org/'
=> "https://acme-staging.api.letsencrypt.org/"
>> require 'acme-client'
=> true
>> client = Acme::Client.new(private_key: private_key, endpoint: endpoint, connection_options: { request: { open_timeout: 5, timeout: 5 } })
=> #<Acme::Client:0x00000001329230 @connection_options={:request=>{:open_timeout=>5, :timeout=>5}}, @directory_uri=nil, @private_key=#<OpenSSL::PKey::RSA:0x00000001708fb8>, @endpoint="https://acme-staging.api.letsencrypt.org/", @nonces=[], @operation_endpoints={"new-authz"=>"/acme/new-authz", "new-cert"=>"/acme/new-cert", "new-reg"=>"/acme/new-reg", "revoke-cert"=>"/acme/revoke-cert"}>
>> registration = client.register(contact: 'mailto:contact@example.com')
Acme::Client::Error::Malformed: algorithm 'none' in JWS header not acceptable
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:37:in `raise_on_error!'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:27:in `on_complete'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `block in call'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client/faraday_middleware.rb:12:in `call'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post'
        from /home/mpalmer/.gem/ruby/2.1.0/gems/acme-client-0.3.3/lib/acme/client.rb:23:in `register'
        from (irb):6
        from /usr/bin/irb:11:in `<main>'
```

I'm working on the assumption that some dependent gem has lost its mind, but I'll file this here in the hope someone else might know more quickly than I can find out.

**Comment by mpalmer** [comment]
Yep, `json-jwt` has apparently changed its API and didn't bother to tell anyone.  Removing 1.6.2 and installing 1.5.2 instead makes things more hunky-dory than they were (things may still break later, but at least the error I reported above is gone now).

Given this problem, and #68, it seems like it might be valuable to fairly tightly constrain the permissible version of `json-jwt` used to known-good versions.

**Comment by jhass** [comment]
Given #33 we actually should just get rid of it as a dependency. It's terribly maintained.

**Comment by unixcharles** [comment]
at this point we might want to simply implement it ourself :(

**Comment by jhass** [comment]
Yes, that thought came to me too.

**Comment by nhinds** [comment]
According to https://github.com/nov/json-jwt/issues/39, `acme-client` should be using the value returned from `jwt.sign` instead of trying to use the object `.sign` was called on and assuming the algorithm should be updated.

Seems to match their readme too. Sad that they changed it in a patch version, but `acme-client` doesn't seem to be using it in the way their docs suggest it should be used
